export const shopCategories = [
    { value: "electronics", label: "Electronics" },
    { value: "fashion", label: "Fashion" },
    { value: "beauty", label: "Beauty & Care" },
    { value: "home", label: "Home & Furniture" },
    { value: "kitchen", label: "Kitchen" },
    { value: "sports", label: "Sports" },
    { value: "toys", label: "Toys" },
    { value: "books", label: "Books" },
    { value: "mobiles", label: "Mobiles & Accessories" },
    { value: "computers", label: "Computers & Laptops" },
    { value: "supermarket", label: "Supermarket" },
    { value: "cars", label: "Cars & Accessories" },
    { value: "pets", label: "Pet Supplies" },
    { value: "jewelry", label: "Jewelry" },
    { value: "handmade", label: "Handmade" },
    { value: "health", label: "Health & Medical" },
    { value: "baby", label: "Baby Products" },
    { value: "garden", label: "Garden & Plants" },
    { value: "office", label: "Office Supplies" },
    { value: "lighting", label: "Lighting" },
    { value: "shoes", label: "Shoes" },
    { value: "bags", label: "Bags" },
    { value: "gaming", label: "Gaming" },
    { value: "stationery", label: "Stationery" },
    { value: "perfumes", label: "Perfumes" },
    { value: "cleaning", label: "Cleaning Supplies" },
    { value: "pharmacy", label: "Pharmacy" },
    { value: "music", label: "Music Instruments" },
    { value: "art", label: "Art & Collectibles" },
];
